---
title: "GSEA"
author: "Jonathan Anzules"
date: "2023-08-06"
output:
# Results come from the the differential analysis names: DGE_Analysis
# Barplots of up/down regulated pathways associated to the differentially expressed genes
---

```{r Set up}
library(fgsea) # pathway enrichment analysis
library(biomaRt) # Converting ensembleID to geneID
library(data.table)
library(plotly)
library(dplyr)
library(tidyr)
library(stringr) # for cleaning gense set names

results <- read.csv("../Data/DGE_Results.csv")
```

# Cleaning and Preparing data
```{r ranka and dfGSEA generation}
# Removing rows with na values in them
results_clean <- results %>% drop_na(log2FoldChange, pvalue)

# Calculating gene rankings
results_clean <- results_clean %>% mutate(rank = log2FoldChange * -log10(pvalue))

# Creating a new dataframe with the necessary columns
dfGSEA <- results_clean %>%
  select(GeneName, log2FC = log2FoldChange, pvalue, rank)
```

```{r Ordered list}
# Extract gene rank and list in decreasing order for GSEA
ranks <- as.numeric(dfGSEA$rank)
names(ranks) <- dfGSEA$GeneName
ranks <- sort(ranks, decreasing=TRUE)
```

```{r}
# Identify duplicates
duplicates <- names(ranks)[duplicated(names(ranks)) | duplicated(names(ranks), fromLast = TRUE)]
print(duplicates)

# Retain the highest value among duplicates
ranks_unique <- tapply(ranks, INDEX = names(ranks), FUN = max)
```

# GO - Pathway Enrichment Analsys
```{r loading gmt file}
# Import .gmt file with pathway information by gene symbol (Gene sets derived from the GO Biological Process ontology)
## Obtained from GSEA 3-6-2023 http://www.gsea-msigdb.org/gsea/msigdb/collections.jsp
go <- gmtPathways("C:/Users/jonan/Documents/Tyseq/Data/c5.go.v2023.1.Hs.symbols.gmt")
```

```{r pathfgsea}
set.seed(06212022)

fgseaRes <- fgsea(pathways = go, 
                  stats = ranks_unique,
                  minSize=6,
                  maxSize=500,
                  nproc=1)
```
##Exploring results
```{r}


SigPath = subset(fgseaRes, pval <= 0.05)
pSigPath = subset(fgseaRes, padj <= 0.1)

dim(SigPath)
dim(pSigPath)
```


## GO - Plotting Pathway Enrichment Analysis

### Picking the top pathways

```{r Saving and Results}
#ssorting by pvalue
fgseaRes <- fgseaRes[order(fgseaRes$pval), ]

# Convert the lists to comma-separated strings
fgseaRes$leadingEdge <- sapply(fgseaRes$leadingEdge, paste, collapse = ",")

# # Save the modified dataframe to a CSV file
# write.csv(fgseaRes, "C:/Users/jonan/Documents/Tyseq/Data/fgseaResults_with_strings_filtered.csv", row.names = FALSE)
# 
# # Read back in the table 
# EAResults <- read.csv("C:/Users/jonan/Documents/Tyseq/Data/fgseaResults_with_strings.csv")

```

```{r Picking Top and up/down pathways - pvalue}

# Select top 10 up and down-regulated pathways
topup <- fgseaRes %>% filter(ES > 0)
topup <- topup[order(topup$pval),]
topup <- topup[1:10,]

topdown <- fgseaRes %>% filter(ES < 0)
topdown <- topdown[order(topdown$pval),]
topdown <- topdown[1:10,]

top <- rbind(topup, rev(topdown))

# Clean up pathway names
top$pathway <- top$pathway %>% str_replace("GO.+?_", "") %>% str_replace_all("_", " ")

top <- top[order(top$pval),]
top <- top %>% filter(pval<=0.05) %>% filter(!is.na(pathway))


# Write cleaned table
write.csv(top, "C:/Users/jonan/Documents/Tyseq/Data/ForReview/Top_GSEA_Pathways_GO_filtered.csv")

```

### Ploting Results
```{r Plotting pathways - Red = downregulated}

# Summarize pathway information and create negative log p value variable for graphing
pathg <- top %>% filter(pval <= 0.1) 
pathg <- pathg %>% mutate(neglogpvalue = -log10(pval))

if (nrow(pathg) >= 1) {
  # Graph pathways by p value
  pathfig <- ggplot(pathg, aes(x = reorder(pathway, neglogpvalue), y = neglogpvalue)) +
    # Conditionally set fill color based on the "ES" value
    geom_bar(aes(fill = ifelse(ES < 0, "red", "black")), stat = "identity") +
    coord_flip() +
    scale_x_discrete(name = "Pathways Associated with Diabetes") +
    scale_fill_identity() +  # Ensure the colors are applied as specified
    ylab("-log(p value)") +
    theme(axis.text.x = element_text(face = "bold", size = 10, angle = 0),
          axis.text.y = element_text(face = "bold", size = 10, angle = 0))

  pathfig

  # Save the figure with increased width (e.g., width = 10 inches)
  # ggsave("C:/Users/jonan/Documents/Tyseq/Figures/Up-Down_GO_pathways.png", width = 12)
  ggsave("../Data/ForReview/Up-Down_GO_pathways2.png", width = 12, dpi = 300)
}


```







# KEGG - Pathway Enrichment Analsys
```{r loading gmt file}
# Import .gmt file with pathway information by gene symbol (Gene sets derived from the GO Biological Process ontology)
## Obtained from GSEA 3-6-2023 http://www.gsea-msigdb.org/gsea/msigdb/collections.jsp
KEGG <- gmtPathways("C:/Users/jonan/Documents/Tyseq/Data/c2.cp.kegg.v2023.1.Hs.symbols.gmt")
```


```{r pathfgsea}
set.seed(06212022)

fgseaRes_kegg <- fgsea(pathways = KEGG, 
                  stats = ranks_unique,
                  minSize=6,
                  maxSize=500,
                  nproc=1)
```
##Exploring results
```{r}

SigPath = subset(fgseaRes_kegg, pval <= 0.05)
pSigPath = subset(fgseaRes_kegg, padj <= 0.1)

dim(SigPath)
dim(pSigPath)
```



## KEGG - Plotting Pathway Enrichment Analysis

### Picking the top pathways

```{r Saving and Results}
#ssorting by pvalue
fgseaRes_kegg <- fgseaRes_kegg[order(fgseaRes_kegg$pval), ]

# Convert the lists to comma-separated strings
fgseaRes_kegg$leadingEdge <- sapply(fgseaRes_kegg$leadingEdge, paste, collapse = ",")

# # Save the modified dataframe to a CSV file
# write.csv(fgseaRes_kegg, "C:/Users/jonan/Documents/Tyseq/Data/fgseaResults_with_strings_filtered.csv", row.names = FALSE)
# 
# # Read back in the table 
# EAResults <- read.csv("C:/Users/jonan/Documents/Tyseq/Data/fgseaResults_with_strings.csv")

```

```{r Picking Top and up/down pathways - pvalue}

# Select top 10 up and down-regulated pathways
topup <- fgseaRes_kegg %>% filter(ES > 0)
topup <- topup[order(topup$pval),]
topup <- topup[1:10,]

topdown <- fgseaRes_kegg %>% filter(ES < 0)
topdown <- topdown[order(topdown$pval),]
topdown <- topdown[1:10,]

top_kegg <- rbind(topup, rev(topdown))

# Clean up pathway names
top_kegg$pathway <- top_kegg$pathway %>% str_replace("KEGG+?_", "") %>% str_replace_all("_", " ")

top_kegg <- top_kegg[order(top_kegg$pval),]
top_kegg <- top_kegg %>% filter(pval<=0.05) %>% filter(!is.na(pathway))


# Write cleaned table
# write_csv(top_kegg, "C:/Users/jonan/Documents/Tyseq/Data/ForReview/top_kegg_GSEA_Pathways_KEGG.csv")

```


### Ploting Results
```{r Plotting pathways - Red = downregulated}

# Summarize pathway information and create negative log p value variable for graphing
pathg <- top_kegg %>% filter(pval <= 0.1) 
pathg <- pathg %>% mutate(neglogpvalue = -log10(pval))

if (nrow(pathg) >= 1) {
  # Graph pathways by p value
  pathfig <- ggplot(pathg, aes(x = reorder(pathway, neglogpvalue), y = neglogpvalue)) +
    # Conditionally set fill color based on the "ES" value
    geom_bar(aes(fill = ifelse(ES < 0, "red", "black")), stat = "identity") +
    coord_flip() +
    scale_x_discrete(name = "Pathways Associated with Diabetes") +
    scale_fill_identity() +  # Ensure the colors are applied as specified
    ylab("-log(p value)") +
    theme(axis.text.x = element_text(face = "bold", size = 10, angle = 0),
          axis.text.y = element_text(face = "bold", size = 10, angle = 0))

  pathfig

  # Save the figure with increased width (e.g., width = 10 inches)
  ggsave("C:/Users/jonan/Documents/Tyseq/Figures/Up-Down_KEGG_pathways.png", width = 12)
  ggsave("../Data/ForReview/Up-Down_KEGG_pathways.png", width = 12, dpi = 300)
}


```